<Project>
  <PropertyGroup>
    <Version>1.27.0</Version>
    <AssemblyVersion>1.27.0.0</AssemblyVersion>
    <FileVersion>1.27.0.0</FileVersion>
    <InformationalVersion>1.27.0</InformationalVersion>
    <Company>SlnU</Company>
    <Product>Atlas</Product>
    <Copyright>Copyright (c) 2026 SlnU</Copyright>
  </PropertyGroup>
</Project>
